# imports
imports_granularity = "Crate"
group_imports = "StdExternalCrate"

# collapse simple code
use_field_init_shorthand = true
use_small_heuristics = "Max"

# comments
format_code_in_doc_comments = true
comment_width = 100
wrap_comments = true
